#!/bin/bash
sum=$(echo "obase=10; ibase=$BASE_WATER; $WATER" | bc) && sum=$(echo "$sum + $(echo "obase=10; ibase=$BASE_STIR; $STIR" | bc)" | bc) && echo $(echo "obase=$BASE_BESTCHOL; ibase=10; $sum" | bc)
