#!/usr/bin/env bash
# debugging nginx (service (init) must say that nginx is not running)
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo kill -9 "$(cat /var/run/nginx.pid)"
