#!/usr/bin/env bash
#Let’s install the ufw firewall and setup a few rules on web-01

sudo apt update
sudo apt install -y ufw
sudo ufw default allow outgoing
sudo ufw default deny incoming
sudo ufw allow 22 (SSH)
sudo ufw allow 443 (HTTPS SSL)
sudo ufw allow 80 (HTTP)
sudo ufw enable   
